name       : haskell-pandoc-types
version    : 1.17.0.5
release    : 1
source     :
    - https://hackage.haskell.org/package/pandoc-types-1.17.0.5/pandoc-types-1.17.0.5.tar.gz : c8825588b587ff5ed0c105156a11a43f3b752279997231cfc13102809bbc51b3
license    : BSD-3-Clause
component  : programming.haskell
summary    : Types for representing a structured document
description: |
    Types for representing a structured document
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
    - haskell-QuickCheck
    - haskell-syb
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
