name       : haskell-pandoc-types
version    : 1.17.4.2
release    : 2
source     :
    - https://hackage.haskell.org/package/pandoc-types-1.17.4.2/pandoc-types-1.17.4.2.tar.gz : 57e15e0a8c74f1acc96259d24eb77a6febbc182a1fd8092af8c431e7a3263eca
license    : BSD-3-Clause
component  : programming.haskell
summary    : Types for representing a structured document
description: |
    Types for representing a structured document
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
    - haskell-QuickCheck
    - haskell-syb
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
