name       : haskell-pandoc-types
version    : 1.17.6.1
release    : 3
source     :
    - https://hackage.haskell.org/package/pandoc-types-1.17.6.1/pandoc-types-1.17.6.1.tar.gz : 1834c2064918a21d346f399c4abcd424617a9a4f0f1e1a8e8ab9b590127edeb4
license    : BSD-3-Clause
component  : programming.haskell
summary    : Types for representing a structured document
description: |
    Types for representing a structured document
builddeps  :
    - haskell-aeson-devel
    - haskell-cabal-install
    - haskell-QuickCheck-devel
    - haskell-syb-devel
rundeps    :
    - devel:
        - haskell-aeson-devel
        - haskell-QuickCheck-devel
        - haskell-syb-devel
networking : yes
setup      : |
    sed -i "s|< 1.5|< 1.6|g" pandoc-types.cabal # aeson
    sed -i "s|< 2.14|< 2.15|g" pandoc-types.cabal # QuickCheck
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
